server:
  auth:
    redirect-ip: http://localhost:3000/
  mongo:
    service: localhost
spring:
  datasource:
    url: jdbc:h2:~/db;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: guan
    password: 123456
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    initialization-mode: always
  data:
    mongodb:
      uri: mongodb://localhost:27017/violin
      transactionEnabled: true

constant:
  docsify-workspace: E:\\

BaiDu:
  AppID: 27103657
  AppKey: BIukdHDXeNPmIXe96GA6OOXGgnP5GEhM
  SecretKey: rFnbg0rnz41UOrSGkGZ0hOISku0sqDOc
  RedirectUri: http://localhost:8080/auth/api/v1/authorize/baidu
  Scope: basic
  AuthorizeUri: http://openapi.baidu.com/oauth/2.0/authorize
  QrCode: 1
  AccessToken: https://openapi.baidu.com/oauth/2.0/token