server:
  port: 8080
  servlet:
    context-path: /auth
spring:
  profiles:
    active: dev
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update # 自动创建表以及更新表结构，生产环境慎用
    show-sql: true # 打印执行的SQL
  h2:
    console:
      path: /h2-console
      enabled: true
redis:
  # redis数据库索引(默认为0)，我们使用索引为3的数据库，避免和其他数据库冲突
  database: 3
  # redis服务器地址（默认为loaclhost）
  host: 192.168.112.130
  # redis端口（默认为6379）
  port: 6379
  # redis访问密码（默认为空）
  password:
  # redis连接超时时间（单位毫秒）
  timeout: 0
  # redis连接池配置
  pool:
    # 最大可用连接数（默认为8，负数表示无限）
    max-active: 8
    # 最大空闲连接数（默认为8，负数表示无限）
    max-idle: 8
    # 最小空闲连接数（默认为0，该值只有为正数才有用）
    min-idle: 0
    # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
    max-wait: -1

BaiDu:
  AppID: 26202308
  AppKey: WksD0FOVAp8zSRV62qNKxtnCexArVPOf
  SecretKey: NWNjqHPRzzZeBcYXh2dNNkMqjZgdEcZY
  RedirectUri: https://www.violin-home.cn/auth/api/v1/authorize/baidu
  Scope: basic
  AuthorizeUri: http://openapi.baidu.com/oauth/2.0/authorize
  QrCode: 1
  AccessToken: https://openapi.baidu.com/oauth/2.0/token